services:
  send2ereader:
    image: goodieshq/send2ereader:latest
    container_name: send2ereader
    restart: unless-stopped
    pull_policy: always
    networks:
      - frontend
    environment:
      PORT: 8080
      CODE_SIZE: 4
      EXPIRATION_MINUTES: 15
    labels:
      traefik.enable: "true"
      traefik.docker.network: frontend
      traefik.http.routers.send2ereader.rule: Host(`s2e.example.com`)
      traefik.http.routers.send2ereader.entrypoints: websecure
      traefik.http.routers.send2ereader.tls: "true"
      traefik.http.routers.send2ereader.tls.certresolver: my_resolver
      traefik.http.services.send2ereader.loadbalancer.server.port: 8080
      traefik.http.services.send2ereader.loadbalancer.server.scheme: http
      traefik.http.routers.send2ereader.service: send2ereader

networks:
  frontend:
    external: true