// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// EreaderPage renders the Kobo/Kindle view.
//
// When downloadURL is empty the file hasn't arrived yet. The page renders a
// "waiting" state and an inline ES5 script that polls /status/{code} every
// 3 seconds. When the server reports the file is ready the script updates the
// DOM in-place — no page reload, no visual flash, works on Kobo ES5 browsers.
//
// When downloadURL is non-empty (e.g. user refreshed after upload) the server
// skips the polling script entirely and renders the download link directly.
func EreaderPage(code, host, downloadURL string, isEreader bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"hero min-h-screen pt-8\"><div class=\"hero-content w-full\" style=\"max-width:28rem\"><div class=\"card w-full bg-base-100 shadow-xl\"><div class=\"card-body gap-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !isEreader {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<h1 class=\"text-2xl uppercase font-black tracking-widest text-transparent bg-clip-text bg-gradient-to-r from-primary to-secondary filter drop-shadow-[0_0_15px_rgba(var(--p),0.5)]\">Send 2 eReader</h1>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<h1 class=\"flex flex-row text-2xl uppercase font-black tracking-widest gap-3\"><span>Send</span> <span>2</span> <span>eReader</span></h1>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<h2 class=\"card-title text-xl\">Send a file to this device</h2>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if downloadURL == "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<p class=\"text-base-content/60 text-sm\">Open a browser on your computer and visit:</p><div class=\"bg-base-200 rounded-box p-5 text-center w-full\"><div class=\"text-xs font-semibold uppercase tracking-widest text-primary mb-2\">Your code</div><div class=\"font-mono font-black text-primary tracking-widest\" style=\"font-size:3.25rem;letter-spacing:0.3em\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(code)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/ereader.templ`, Line: 32, Col: 124}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></div><p class=\"text-base-content/60 text-sm\">Go to <strong class=\"text-base-content\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(host)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/ereader.templ`, Line: 35, Col: 54}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</strong>, enter the code above, pick your file and hit send.</p><div id=\"s2e-status\" data-code=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(code)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/ereader.templ`, Line: 37, Col: 44}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" class=\"w-full\"><div id=\"s2e-waiting\" role=\"alert\" class=\"alert alert-warning\"><span class=\"loading loading-spinner loading-sm\"></span> <span>Waiting for file from your computer&hellip;</span></div><div id=\"s2e-ready\" style=\"display:none\"><div role=\"alert\" class=\"alert alert-success mb-3\"><span>&#10003; File received!</span></div><a id=\"s2e-link\" class=\"btn btn-primary btn-block btn-lg flex-wrap whitespace-normal break-words\" href=\"#\" download>&#8681;&nbsp; Download your file</a></div></div><script>\n(function () {\n  var root    = document.getElementById('s2e-status');\n  var waiting = document.getElementById('s2e-waiting');\n  var ready   = document.getElementById('s2e-ready');\n  var link    = document.getElementById('s2e-link');\n  var code    = root.getAttribute('data-code');\n  var timer   = null;\n\n  function poll() {\n    var xhr = new XMLHttpRequest();\n    xhr.onload = function () {\n      if (xhr.status === 200) {\n        var data;\n        try { data = JSON.parse(xhr.responseText); } catch (e) { return; }\n        if (data.ready) {\n          if (timer !== null) { clearInterval(timer); timer = null; }\n          link.href = '/download/' + code;\n          if (data.filename) {\n            link.lastChild.nodeValue = ' Download ' + data.filename;\n          }\n          waiting.style.display = 'none';\n          ready.style.display   = 'block';\n        }\n      } else if (xhr.status === 404) {\n        if (timer !== null) { clearInterval(timer); timer = null; }\n        waiting.innerHTML = '<span>&#9888; Session expired. Refresh the page to get a new code.</span>';\n      }\n    };\n    xhr.onerror = function () {};\n    xhr.open('GET', '/status/' + code, true);\n    xhr.send(null);\n  }\n\n  timer = setInterval(poll, 3000);\n  poll();\n})();\n\t\t\t\t\t\t\t</script>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<p class=\"text-base-content/60 text-sm\">Your file is ready to download.</p><div role=\"alert\" class=\"alert alert-success\"><span>&#10003; File received!</span></div><a class=\"btn btn-primary btn-block btn-lg\" href=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 templ.SafeURL
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(downloadURL))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/ereader.templ`, Line: 94, Col: 84}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\">&#8681;&nbsp; Download your file</a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Your Code", false).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
